### ISSUE TITLE
:art: :house: Homepage

### ISSUE THREAD

**Issue by NewtonOmbese** [NewtonOmbese/haipcrm#1]
Creation of a responsive home design having all text centered and at the center of the page as in the design below

![homepage](https://user-images.githubusercontent.com/79839603/229609520-5f5334c1-f6fc-45f7-8b30-09e51b0620a5.png)

**Comment by carreuky** [comment]
Working on this.

**Comment by carreuky** [comment]
Pushed the code change the whole webpage site and color to avoid affecting everything.
